### PR TITLE
fix: fmt, minor issues and update

### PR DESCRIPTION
**Pull request by botika**
Fix minor issues. 
I have put the typical configurations in a rust project for `gitignore` and fixed an error when not using the reference as an argument of the function so it forces to pass its owned without the need for it.

### CODE REVIEW

**Comment by christoshadjiaslanis** [comment]
Thanks for this @botika. Will review in the morning and merge!

**Comment by botika** [comment]
Have you closed the job offer? Well, it seems that there is still a lot of work.

**Comment by christoshadjiaslanis** [comment]
> Have you closed the job offer? Well, it seems that there is still a lot of work.

Hey! No we just made a new posting for admin reasons. We still have 2 openings. I've reached out to you over email :smile:

**Comment by botika** [comment]
> > Have you closed the job offer? Well, it seems that there is still a lot of work.
> 
> Hey! No we just made a new posting for admin reasons. We still have 2 openings. I've reached out to you over email smile

Nice! Disappeared on LinkedIn and scared me :smile:. I've already confirmed I'll see you tomorrow.

**Comment by hbina** [comment]
According to this, applications should lock `Cargo.lock`. https://github.com/rust-lang/cargo/issues/315#issuecomment-51075730

**Pull request closed without merging**
